---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: "nuget"
    directory: "benchmark/01-empty-app/DotnetMaui"
    schedule:
      interval: monthly
  - package-ecosystem: "nuget"
    directory: "benchmark/01-empty-app/DotnetMauiVue"
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: "benchmark/01-empty-app/electron"
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: "benchmark/01-empty-app/nodegui"
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: "benchmark/01-empty-app/nw.js"
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: "benchmark/01-empty-app/tauri"
    schedule:
      interval: monthly
  - package-ecosystem: cargo
    directory: "benchmark/01-empty-app/tauri/src-tauri"
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: "benchmark/01-empty-app/wails/frontend"
    schedule:
      interval: monthly
  - package-ecosystem: gomod
    directory: "benchmark/01-empty-app/wails"
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: "benchmark/02-empty-app-frameless/electron"
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: "benchmark/02-empty-app-frameless/nodegui"
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: "benchmark/02-empty-app-frameless/nw.js"
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: "benchmark/02-empty-app-frameless/tauri"
    schedule:
      interval: monthly
  - package-ecosystem: cargo
    directory: "benchmark/02-empty-app-frameless/tauri/src-tauri"
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: runner
    schedule:
      interval: monthly
