name: Runner

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
  
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Git pull # Needed for sequential run
        run: git pull

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 18

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      # Setup Java environment in order to build the Android app.
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v2

      - name:  Install
        run:   |
               if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
                    sudo apt update
                    sudo apt install -y libxshmfence1 libglu1 libnss3 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libasound2 # Electron
                    sudo apt install -y libwebkit2gtk-4.0-37 libstdc++6 # NeutralinoJS
                    sudo apt install -y pkg-config build-essential cmake make mesa-common-dev libglu1-mesa-dev # NodeGUI
               else
                    echo "Nothing to install on $RUNNER_OS"
               fi
        shell: bash

      - name: Install runner tools
        run: |
          cd runner/
          npm i

      - name: Prepare environments
        run: |
          cd runner/
          bash preprocess.sh

      - name: Run apps
        run: |
          cd runner/
          node runner.js

      - name: Update README
        run: |
          cd runner/
          node writer.js

      - name: Git status
        run: git status

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update benchmark
          file_pattern: runner/benchmarks.json README.md
