name: Runner

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  npm_config_yes: true

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        app: [01-empty-app, 02-empty-app-frameless]
  
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Git pull # Needed for sequential run
        run: git pull

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16 # Warning: nodegui doesn't support node 18 yet

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      # Setup Java environment in order to build the Android app.
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18.x'

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v2

      - name:  Install
        run:   |
               if [ "$RUNNER_OS" == "Linux" ]; then
                    sudo apt update
                    sudo apt install -y xvfb # X Server
                    sudo apt install -y libxshmfence1 libglu1 libnss3 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libasound2 # Electron
                    sudo apt install -y libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev # Tauri
                    sudo apt install -y libwebkit2gtk-4.0-dev libstdc++6 # NeutralinoJS
                    sudo apt install -y pkg-config build-essential cmake make mesa-common-dev libglu1-mesa-dev file libqt5core5a libqt5dbus5 libqt5gui5 libqt5network5 libqt5printsupport5 libqt5svg5 libqt5widgets5 # NodeGUI
               else
                    echo "Nothing to install on $RUNNER_OS"
               fi
        shell: bash

      - name: Install runner tools
        run: |
          cd runner/
          npm i

      - name: Prepare environments
        run: |
          cd runner/
          bash preprocess.sh ${{ matrix.app }}

      - name: Run apps
        run: |
          cd runner/
          if [ "$RUNNER_OS" == "Linux" ]; then
            LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/home/runner/work/web-to-desktop-framework-comparison/web-to-desktop-framework-comparison/benchmark/01-empty-app/nodegui/node_modules/@nodegui/nodegui/miniqt/5.15.2/gcc_64/lib/" xvfb-run --auto-servernum node runner.js ${{ matrix.app }}
          else
            node runner.js ${{ matrix.app }}
          fi
        shell: bash

      - name: Update README
        run: |
          cd runner/
          node writer.js

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update benchmark for ${{ matrix.app }} on ${{ matrix.os }}
          file_pattern: runner/benchmarks.json README.md
