name: Stars & Fork

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # so we can commit --amend and push -f
          fetch-depth: 2

      - name: Git pull # Needed for sequential run
        run: git pull

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 18

      - name: Run apps
        run: |
          cd runner/
          npm ci
          node stats.js
        shell: bash

      - name: Update README
        run: |
          cd runner/
          node writer.js

      - name: Get last commit message
        id: last-commit-message
        run: |
          echo "::set-output name=msg::$(git log -1 --pretty=%s)"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "${{ steps.last-commit-message.outputs.msg }}\n* Update stars & Fork"
          commit_options: '--amend --no-edit'
          push_options: '--force'
          skip_fetch: true
          file_pattern: runner/stats.json README.md