name: Stars & Fork

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # so we can commit --amend and push -f
          fetch-depth: 2

      - name: Git pull # Needed for sequential run
        run: git pull

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 22

      - name: Run apps
        run: |
          cd runner/
          npm ci
          node stats.js
        shell: bash

      - name: Update README/GRAPHS
        run: |
          cd runner/
          node write_readme.js
          node write_graphsdotmd.js

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Update stars & Fork"
          file_pattern: runner/stats.json README.md GRAPHS.md